// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInbound(arg1) {
  return window['go']['app']['App']['AddInbound'](arg1);
}

export function AddInboundTx(arg1, arg2) {
  return window['go']['app']['App']['AddInboundTx'](arg1, arg2);
}

export function AddItem(arg1) {
  return window['go']['app']['App']['AddItem'](arg1);
}

export function AddOutbound(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['AddOutbound'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddStock(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddStock'](arg1, arg2, arg3);
}

export function AddSupplier(arg1) {
  return window['go']['app']['App']['AddSupplier'](arg1);
}

export function AddWarehouse(arg1) {
  return window['go']['app']['App']['AddWarehouse'](arg1);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function ChangeStock(arg1, arg2, arg3) {
  return window['go']['app']['App']['ChangeStock'](arg1, arg2, arg3);
}

export function ChangeUserData(arg1) {
  return window['go']['app']['App']['ChangeUserData'](arg1);
}

export function DeleteInbound(arg1) {
  return window['go']['app']['App']['DeleteInbound'](arg1);
}

export function EditInbound(arg1) {
  return window['go']['app']['App']['EditInbound'](arg1);
}

export function EditOutbound(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['EditOutbound'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function EditSupplier(arg1) {
  return window['go']['app']['App']['EditSupplier'](arg1);
}

export function EditWarehouse(arg1) {
  return window['go']['app']['App']['EditWarehouse'](arg1);
}

export function ExportDeliveriesToExcel() {
  return window['go']['app']['App']['ExportDeliveriesToExcel']();
}

export function ExportItemsToExcel() {
  return window['go']['app']['App']['ExportItemsToExcel']();
}

export function ExportStockToExcel() {
  return window['go']['app']['App']['ExportStockToExcel']();
}

export function ExportSuppliersToExcel() {
  return window['go']['app']['App']['ExportSuppliersToExcel']();
}

export function ExportUsersToExcel() {
  return window['go']['app']['App']['ExportUsersToExcel']();
}

export function FindItems(arg1) {
  return window['go']['app']['App']['FindItems'](arg1);
}

export function FindStockByWarehouse(arg1) {
  return window['go']['app']['App']['FindStockByWarehouse'](arg1);
}

export function GetAllItems() {
  return window['go']['app']['App']['GetAllItems']();
}

export function GetAllMovementsThisMonth() {
  return window['go']['app']['App']['GetAllMovementsThisMonth']();
}

export function GetDashboard() {
  return window['go']['app']['App']['GetDashboard']();
}

export function GetInboundDetails() {
  return window['go']['app']['App']['GetInboundDetails']();
}

export function GetInboundDetailsByDate(arg1) {
  return window['go']['app']['App']['GetInboundDetailsByDate'](arg1);
}

export function GetItems() {
  return window['go']['app']['App']['GetItems']();
}

export function GetOutboundDetails() {
  return window['go']['app']['App']['GetOutboundDetails']();
}

export function GetStockDetails() {
  return window['go']['app']['App']['GetStockDetails']();
}

export function GetStockTransfers() {
  return window['go']['app']['App']['GetStockTransfers']();
}

export function GetStocks() {
  return window['go']['app']['App']['GetStocks']();
}

export function GetSuppliers() {
  return window['go']['app']['App']['GetSuppliers']();
}

export function GetTopItems() {
  return window['go']['app']['App']['GetTopItems']();
}

export function GetTurnoverByWarehouse() {
  return window['go']['app']['App']['GetTurnoverByWarehouse']();
}

export function GetUsers() {
  return window['go']['app']['App']['GetUsers']();
}

export function GetWarehouses() {
  return window['go']['app']['App']['GetWarehouses']();
}

export function GetWeeklyStockTrend() {
  return window['go']['app']['App']['GetWeeklyStockTrend']();
}

export function LoginUser(arg1, arg2) {
  return window['go']['app']['App']['LoginUser'](arg1, arg2);
}

export function RegisterUser(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RegisterUser'](arg1, arg2, arg3, arg4);
}

export function RemoveItem(arg1) {
  return window['go']['app']['App']['RemoveItem'](arg1);
}

export function RemoveOutbound(arg1) {
  return window['go']['app']['App']['RemoveOutbound'](arg1);
}

export function RemoveStock(arg1) {
  return window['go']['app']['App']['RemoveStock'](arg1);
}

export function RemoveSupplier(arg1) {
  return window['go']['app']['App']['RemoveSupplier'](arg1);
}

export function RemoveUser(arg1) {
  return window['go']['app']['App']['RemoveUser'](arg1);
}

export function TransferStock(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['TransferStock'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateItem(arg1) {
  return window['go']['app']['App']['UpdateItem'](arg1);
}
